@extends('layouts.app')

<p> Merchandise and Ticket Listings </p>
<div id="listing">

<div class="form-group{{ $errors->has('ticketOrMerch') ? ' has-error' : '' }}">
    <label for="ticketOrMerch" class="col-md-4 control-label">Ticket or Merchandise? (Note: If the ticket
      comes with merchandise, please select ticket for our invoice purposes)</label>
    <div class="col-md-6">
        <input id="ticketOrMerch" type="radio" class="form-control" name="ticketOrMerch" vale="ticket"> Ticket
        <input id="ticketOrMerch" type="radio" class="form-control" name="ticketOrMerch" vale="merch"> Merchandise
    </div>
</div>

  <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
      <label for="title" class="col-md-4 control-label">What is it?</label>
      <div class="col-md-6">
          <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}">
          @if ($errors->has('title'))
              <span class="help-block">
                  <strong>{{ $errors->first('title') }}</strong>
              </span>
          @endif
      </div>
  </div>
  <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
      <label for="description" class="col-md-4 control-label">Describe what you're selling </label>
      <div class="col-md-6">
          <textarea id="description" class="form-control" name="title[]" value="{{ old('description') }}"></textarea>
          @if ($errors->has('description'))
              <span class="help-block">
                  <strong>{{ $errors->first('description') }}</strong>
              </span>
          @endif
      </div>
  </div>
  <div class="form-group{{ $errors->has('merchImage') ? ' has-error' : '' }}">
      <label for="merchImage" class="col-md-4 control-label"> Picture of what you're selling (optional) </label>
      <div class="col-md-6">
          <input type="file" id="merchImage" class="form-control" name="merchImage[]" value="{{ old('merchImage') }}">
          @if ($errors->has('merchImage'))
              <span class="help-block">
                  <strong>{{ $errors->first('merchImage') }}</strong>
              </span>
          @endif
      </div>
  </div>
  <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
      <label for="price" class="col-md-4 control-label">Price </label>
      <div class="col-md-6">
          <input type="number" id="price" class="form-control" name="price[]" value="{{ old('price') }}">
          @if ($errors->has('price'))
              <span class="help-block">
                  <strong>{{ $errors->first('price') }}</strong>
              </span>
          @endif
      </div>
  </div>
  <div class="form-group{{ $errors->has('quantity') ? ' has-error' : '' }}">
      <label for="quantity" class="col-md-4 control-label">Quantity Available (if applicable) </label>
      <div class="col-md-6">
          <input type="number" id="quantity" class="form-control" name="quantity[]" value="{{ old('quantity') }}">
          @if ($errors->has('quantity'))
              <span class="help-block">
                  <strong>{{ $errors->first('quantity') }}</strong>
              </span>
          @endif
      </div>
  </div>
  <div class="form-group{{ $errors->has('delivery_method') ? ' has-error' : '' }}">
      <label for="delivery_method" class="col-md-4 control-label">Delivery Method </label>
      <div class="col-md-6">
          <input id="delivery_method" type="radio" class="form-control" name="delivery_methodh[]" vale="Auto"> Autogenerated Email (
          available for tickets only)
          <input id="delivery_method" type="radio" class="form-control" name="delivery_method[]" vale="Pickup"> Pickup
          <input id="delivery_method" type="radio" class="form-control" name="delivery_method[]" vale="Delivery"> Delivery
      </div>
  </div>
<div class="form-group{{ $errors->has('delivery_details') ? ' has-error' : '' }}">
    <label for="delivery_details" class="col-md-4 control-label">Delivery Details </label>
    <div class="col-md-6">
      <textarea id="delivery_details" class="form-control" name="delivery_details[]" value="{{ old('delivery_details') }}">Provide any
      information on where to pick up merchandise or tickets, how to specify delivery, etc. </textarea>
      @if ($errors->has('delivery_details'))
          <span class="help-block">
              <strong>{{ $errors->first('delivery_details') }}</strong>
          </span>
      @endif
    </div>
</div>
</div>
<button action="" class="btn btn-primary">Add Item</button>
